name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Grant execute permission for gradlew And Run Gradlew
      run: |
chmod +x gradlew
 ./gradlew build
