name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew And Run Gradlew
      run: |
chmod +x gradlew
 ./gradlew build

      - name: 'Upload Artifact'
    uses: actions/upload-artifact@v3
    with:
      name: ros-debug.apk
      path: build/outputs/apk/*.apk
